# Generated by Django 3.1.4 on 2021-01-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_auto_20210114_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bow',
            name='owned_bow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='owned_rifle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='owned_shotgun',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sniper',
            name='owned_sniper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zhuge',
            name='owned_zhuge',
            field=models.BooleanField(default=False),
        ),
    ]
