# Generated by Django 3.1.4 on 2021-01-14 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0003_auto_20210114_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bow',
            name='blueprint_bow',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bow',
            name='grip_bow',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bow',
            name='lower_bow',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bow',
            name='string_bow',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bow',
            name='upper_bow',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bow',
            name='user_bow',
            field=models.CharField(default='LethalisUmbra', max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)]),
        ),
    ]
