# Generated by Django 3.1.4 on 2021-01-15 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0004_auto_20210114_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bow',
            old_name='user_bow',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='rifle',
            name='user_rifle',
        ),
        migrations.RemoveField(
            model_name='shotgun',
            name='user_shotgun',
        ),
        migrations.RemoveField(
            model_name='sniper',
            name='user_sniper',
        ),
        migrations.RemoveField(
            model_name='zhuge',
            name='user_zhuge',
        ),
        migrations.AddField(
            model_name='rifle',
            name='owner',
            field=models.CharField(default='LethalisUmbra', max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='shotgun',
            name='owner',
            field=models.CharField(default='LethalisUmbra', max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='sniper',
            name='owner',
            field=models.CharField(default='LethalisUmbra', max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='zhuge',
            name='owner',
            field=models.CharField(default='LethalisUmbra', max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='barrel_rifle',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='blueprint_rifle',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='receiver_rifle',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='stock_rifle',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='barrel_shotgun',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='blueprint_shotgun',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='receiver_shotgun',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shotgun',
            name='stock_shotgun',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sniper',
            name='barrel_sniper',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sniper',
            name='blueprint_sniper',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sniper',
            name='receiver_sniper',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sniper',
            name='stock_sniper',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zhuge',
            name='barrel_zhuge',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zhuge',
            name='blueprint_zhuge',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zhuge',
            name='grip_zhuge',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zhuge',
            name='receiver_zhuge',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zhuge',
            name='string_zhuge',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
