from django.contrib import admin
from .models import *

admin.site.register(AK)
admin.site.register(Archwing)
admin.site.register(Ballista)
admin.site.register(Claws)
admin.site.register(Collar)
admin.site.register(Dagger)
admin.site.register(Dual)
admin.site.register(Dual_Dagger)
admin.site.register(Dual_Swords)
admin.site.register(Fist)
admin.site.register(Glaive)
admin.site.register(Gunblade)
admin.site.register(Hammer)
admin.site.register(Heavy_Blade)
admin.site.register(Nikana)
admin.site.register(Nunchaku)
admin.site.register(Pistol)
admin.site.register(Polearm)
admin.site.register(Rapier)

admin.site.register(Scythe)
admin.site.register(Sentinel)

admin.site.register(Shotgun_Sidearm)

admin.site.register(Sparring)
admin.site.register(Staff)
admin.site.register(Sword)
admin.site.register(Sword_Shield)
admin.site.register(Thrown)
admin.site.register(Tonfa)
admin.site.register(Warframe)
