# Generated by Django 3.1.2 on 2020-10-10 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AK',
            fields=[
                ('id_ak', models.AutoField(primary_key=True, serialize=False)),
                ('name_ak', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_ak', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('barrel_ak', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('receiver_ak', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('link_ak', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owne_ak', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Archwing',
            fields=[
                ('id_archwing', models.AutoField(primary_key=True, serialize=False)),
                ('name_archwing', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_archwing', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('harness_archwing', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('wings_archwing', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('systems_archwing', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_archwing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ballista',
            fields=[
                ('id_ballista', models.AutoField(primary_key=True, serialize=False)),
                ('name_ballista', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_ballista', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('upper_ballista', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('lower_ballista', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('string_ballista', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('receiver_ballista', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_ballista', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('id_bow', models.AutoField(primary_key=True, serialize=False)),
                ('name_bow', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_bow', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('upper_bow', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('lower_bow', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('grip_bow', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('string_bow', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_sniper', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Claws',
            fields=[
                ('id_claws', models.AutoField(primary_key=True, serialize=False)),
                ('name_claws', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_claws', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_claws', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('guantlet_claws', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_claws', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Collar',
            fields=[
                ('id_collar', models.AutoField(primary_key=True, serialize=False)),
                ('name_collar', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_collar', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('band_collar', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('buckle_collar', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_collar', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dagger',
            fields=[
                ('id_dagger', models.AutoField(primary_key=True, serialize=False)),
                ('name_dagger', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_dagger', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_dagger', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_dagger', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_dagger', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dual',
            fields=[
                ('id_dual', models.AutoField(primary_key=True, serialize=False)),
                ('name_dual', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('single_dual', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('link_dual', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_dual', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dual_Dagger',
            fields=[
                ('id_dual_dagger', models.AutoField(primary_key=True, serialize=False)),
                ('name_dual_dagger', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_dual_dagger', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_dual_dagger', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_dual_dagger', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_dual_dagger', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dual_Swords',
            fields=[
                ('id_dual_swords', models.AutoField(primary_key=True, serialize=False)),
                ('name_dual_swords', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_dual_swords', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_dual_swords', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_dual_swords', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_dual_swords', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fist',
            fields=[
                ('id_fist', models.AutoField(primary_key=True, serialize=False)),
                ('name_fist', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_fist', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_fist', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('guantlet_fist', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_fist', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Glaive',
            fields=[
                ('id_glaive', models.AutoField(primary_key=True, serialize=False)),
                ('name_glaive', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_glaive', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_glaive', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('disc_glaive', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_glaive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Gunblade',
            fields=[
                ('id_gunblade', models.AutoField(primary_key=True, serialize=False)),
                ('name_gunblade', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_gunblade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_gunblade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_gunblade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_gunblade', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Hammer',
            fields=[
                ('id_hammer', models.AutoField(primary_key=True, serialize=False)),
                ('name_hammer', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_hammer', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('head_hammer', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_hammer', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_hammer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Heavy_Blade',
            fields=[
                ('id_heavy', models.AutoField(primary_key=True, serialize=False)),
                ('name_heavy', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_heavy', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_heavy', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_heavy', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_heavy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Nikana',
            fields=[
                ('id_nikana', models.AutoField(primary_key=True, serialize=False)),
                ('name_nikana', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_nikana', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('hilt_nikana', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_nikana', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_nikana', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Nunchaku',
            fields=[
                ('id_nunchaku', models.AutoField(primary_key=True, serialize=False)),
                ('name_nunchaku', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_nunchaku', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_nunchaku', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('chain_nunchaku', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_nunchaku', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pistol',
            fields=[
                ('id_pistol', models.AutoField(primary_key=True, serialize=False)),
                ('name_pistol', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_pistol', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('barrel_pistol', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('receiver_pistol', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_pistol', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Polearm',
            fields=[
                ('id_polearm', models.AutoField(primary_key=True, serialize=False)),
                ('name_polearm', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_polearm', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_polearm', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_polearm', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_polearm', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rapier',
            fields=[
                ('id_rapier', models.AutoField(primary_key=True, serialize=False)),
                ('name_rapier', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_rapier', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_rapier', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_rapier', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_rapier', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rifle',
            fields=[
                ('id_rifle', models.AutoField(primary_key=True, serialize=False)),
                ('name_rifle', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_rifle', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('barrel_rifle', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('receiver_rifle', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('stock_rifle', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_rifle', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Scythe',
            fields=[
                ('id_scythe', models.AutoField(primary_key=True, serialize=False)),
                ('name_scythe', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_scythe', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_scythe', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_scythe', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_scythe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentinel',
            fields=[
                ('id_sentinel', models.AutoField(primary_key=True, serialize=False)),
                ('name_sentinel', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_sentinel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('cerebrum_sentinel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('carapace_sentinel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('systems_sentinel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_sentinel', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shotgun',
            fields=[
                ('id_shotgun', models.AutoField(primary_key=True, serialize=False)),
                ('name_shotgun', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_shotgun', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('barrel_shotgun', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('receiver_shotgun', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('stock_shotgun', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_shotgun', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shotgun_Sidearm',
            fields=[
                ('id_sidearm', models.AutoField(primary_key=True, serialize=False)),
                ('name_sidearm', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_sidearm', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('barrel_sidearm', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('receiver_sidearm', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_sidearm', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sniper',
            fields=[
                ('id_sniper', models.AutoField(primary_key=True, serialize=False)),
                ('name_sniper', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_sniper', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('barrel_sniper', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('receiver_sniper', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('stock_sniper', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_sniper', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sparring',
            fields=[
                ('id_sparring', models.AutoField(primary_key=True, serialize=False)),
                ('name_sparring', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_sparring', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('gauntlet_sparring', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('boot_sparring', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_sparring', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id_staff', models.AutoField(primary_key=True, serialize=False)),
                ('name_staff', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_staff', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('ornament_staff', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_staff', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_staff', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sword',
            fields=[
                ('id_sword', models.AutoField(primary_key=True, serialize=False)),
                ('name_sword', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_sword', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_sword', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_sword', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_sword', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sword_Shield',
            fields=[
                ('id_shield', models.AutoField(primary_key=True, serialize=False)),
                ('name_shield', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_shield', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_shield', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('guard_shield', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('hilt_shield', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_shield', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Thrown',
            fields=[
                ('id_thrown', models.AutoField(primary_key=True, serialize=False)),
                ('name_thrown', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_thrown', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('pouch_thrown', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('starts_thrown', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_thrown', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tonfa',
            fields=[
                ('id_tonfa', models.AutoField(primary_key=True, serialize=False)),
                ('name_tonfa', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_tonfa', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('blade_tonfa', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('handle_tonfa', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_tonfa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Warframe',
            fields=[
                ('id_warframe', models.AutoField(primary_key=True, serialize=False)),
                ('name_warframe', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_warframe', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('neuroptics_warframe', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('chassis_warframe', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('systems_warframe', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_warframe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Zhuge',
            fields=[
                ('id_zhuge', models.AutoField(primary_key=True, serialize=False)),
                ('name_zhuge', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('blueprint_zhuge', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('grip_zhuge', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('string_zhuge', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('barrel_zhuge', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('receiver_zhuge', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('owned_zhuge', models.BooleanField()),
            ],
        ),
    ]
