# Generated by Django 3.1.2 on 2020-10-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ak',
            old_name='owne_ak',
            new_name='owned_ak',
        ),
    ]
