# Generated by Django 3.1.2 on 2020-10-10 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201010_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pistol',
            name='name_pistol',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
