# Generated by Django 3.1.4 on 2021-01-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20201010_0011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bow',
        ),
        migrations.DeleteModel(
            name='Rifle',
        ),
        migrations.DeleteModel(
            name='Shotgun',
        ),
        migrations.DeleteModel(
            name='Sniper',
        ),
        migrations.DeleteModel(
            name='Zhuge',
        ),
    ]
